const busData = [
  {
    id: 1,
    operator: "SRS Travels",
    busType: "AC Sleeper (2+1)",
    layoutType: "SLEEPER_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "20:45",
    arrivalTime: "05:00",
    duration: "8h 15m",
    date: "17 Sep 2026",
    price: 580,
    seats: 36,
    rating: 4.2,
    reviews: "1.2K",
    amenities: ["WiFi", "Charging", "Blanket", "Water Bottle"],
  },
  {
    id: 2,
    operator: "VRL Travels",
    busType: "AC Couple Sleeper (2+1)",
    layoutType: "SLEEPER_COUPLE_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "21:30",
    arrivalTime: "06:15",
    duration: "8h 45m",
    date: "17 Sep 2026",
    price: 650,
    seats: 36,
    rating: 4.6,
    reviews: "2.4K",
    amenities: ["WiFi", "Charging", "Couple Berths", "Pillow", "Blanket"],
  },
  {
    id: 3,
    operator: "Orange Travels",
    busType: "AC Seater/Sleeper (2+1)",
    layoutType: "HYBRID_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "22:00",
    arrivalTime: "06:30",
    duration: "8h 30m",
    date: "17 Sep 2026",
    price: 850,
    seats: 32,
    rating: 4.3,
    reviews: "1.5K",
    amenities: ["WiFi", "Charging", "Blanket", "Live Tracking"],
  },
  {
    id: 4,
    operator: "IntrCity SmartBus",
    busType: "AC Couple Sleeper (2+2)",
    layoutType: "SLEEPER_COUPLE_2_2",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "19:45",
    arrivalTime: "04:30",
    duration: "8h 45m",
    date: "17 Sep 2026",
    price: 790,
    seats: 32,
    rating: 4.7,
    reviews: "3.1K",
    amenities: ["WiFi", "Couple Berths", "Charging", "Snacks", "Pillow"],
  },
  {
    id: 5,
    operator: "Neeta Travels",
    busType: "AC Sleeper (2+2)",
    layoutType: "SLEEPER_2_2",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "23:00",
    arrivalTime: "07:30",
    duration: "8h 30m",
    date: "17 Sep 2026",
    price: 950,
    seats: 32,
    rating: 4.1,
    reviews: "1.1K",
    amenities: ["WiFi", "Charging", "Blanket", "Pillow"],
  },
  {
    id: 6,
    operator: "Patel Travels",
    busType: "Non-AC Seater (2+3)",
    layoutType: "SEATER_2_3",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "18:30",
    arrivalTime: "03:30",
    duration: "9h 00m",
    date: "17 Sep 2026",
    price: 490,
    seats: 45,
    rating: 3.9,
    reviews: "920",
    amenities: ["Charging", "Water Bottle"],
  },
  {
    id: 7,
    operator: "Zingbus",
    busType: "AC Seater/Sleeper (2+2)",
    layoutType: "HYBRID_2_2",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "20:15",
    arrivalTime: "04:45",
    duration: "8h 30m",
    date: "17 Sep 2026",
    price: 890,
    seats: 36,
    rating: 4.4,
    reviews: "1.8K",
    amenities: ["WiFi", "Charging", "Blanket", "Water Bottle"],
  },
  {
    id: 8,
    operator: "Rajdhani Express",
    busType: "Semi Sleeper (2+2)",
    layoutType: "SEMI_SLEEPER_2_2",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "23:45",
    arrivalTime: "08:15",
    duration: "8h 30m",
    date: "17 Sep 2026",
    price: 680,
    seats: 32,
    rating: 4.0,
    reviews: "740",
    amenities: ["Charging", "Reclining Seats", "Water Bottle"],
  },
  {
    id: 9,
    operator: "National Travels",
    busType: "Non-AC Sleeper (2+1)",
    layoutType: "SLEEPER_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "19:00",
    arrivalTime: "04:00",
    duration: "9h 00m",
    date: "17 Sep 2026",
    price: 550,
    seats: 36,
    rating: 3.7,
    reviews: "480",
    amenities: ["Charging", "Blanket"],
  },
  {
    id: 10,
    operator: "Jabbar Travels",
    busType: "AC Couple Sleeper (2+1)",
    layoutType: "SLEEPER_COUPLE_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "21:00",
    arrivalTime: "05:30",
    duration: "8h 30m",
    date: "17 Sep 2026",
    price: 740,
    seats: 36,
    rating: 4.5,
    reviews: "1.9K",
    amenities: ["WiFi", "Couple Berths", "Pillow", "Blanket"],
  },
  {
    id: 11,
    operator: "Morning Star Travels",
    busType: "AC Seater (2+2)",
    layoutType: "SEATER_2_2",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "17:30",
    arrivalTime: "02:00",
    duration: "8h 30m",
    date: "17 Sep 2026",
    price: 620,
    seats: 36,
    rating: 4.3,
    reviews: "1.4K",
    amenities: ["WiFi", "Charging", "Water Bottle"],
  },
  {
    id: 12,
    operator: "GreenLine Travels",
    busType: "Volvo Multi-Axle AC Sleeper (2+1)",
    layoutType: "SLEEPER_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "22:15",
    arrivalTime: "06:30",
    duration: "8h 15m",
    date: "17 Sep 2026",
    price: 920,
    seats: 36,
    rating: 4.8,
    reviews: "3.5K",
    amenities: ["WiFi", "Charging", "Movie Screens", "Blanket", "Water Bottle"],
  },
  {
    id: 13,
    operator: "KRL Travels",
    busType: "AC Seater (2+1)",
    layoutType: "SEATER_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "16:00",
    arrivalTime: "01:00",
    duration: "9h 00m",
    date: "17 Sep 2026",
    price: 590,
    seats: 28,
    rating: 4.1,
    reviews: "830",
    amenities: ["Charging", "Reclining Seats", "Water Bottle"],
  },
  {
    id: 14,
    operator: "Seabird Travels",
    busType: "Non-AC Seater/Sleeper (2+1)",
    layoutType: "HYBRID_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "18:00",
    arrivalTime: "03:00",
    duration: "9h 00m",
    date: "17 Sep 2026",
    price: 510,
    seats: 32,
    rating: 3.8,
    reviews: "620",
    amenities: ["Charging", "Water Bottle"],
  },
  {
    id: 15,
    operator: "Hans Travels",
    busType: "AC Couple Sleeper (2+2)",
    layoutType: "SLEEPER_COUPLE_2_2",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "20:30",
    arrivalTime: "05:00",
    duration: "8h 30m",
    date: "17 Sep 2026",
    price: 820,
    seats: 32,
    rating: 4.4,
    reviews: "1.6K",
    amenities: ["WiFi", "Couple Berths", "Blanket", "Charging"],
  },
  {
    id: 16,
    operator: "Sharma Travels",
    busType: "Non-AC Seater (2+2)",
    layoutType: "SEATER_2_2",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "15:00",
    arrivalTime: "00:00",
    duration: "9h 00m",
    date: "17 Sep 2026",
    price: 420,
    seats: 36,
    rating: 3.6,
    reviews: "390",
    amenities: ["Water Bottle"],
  },
  {
    id: 17,
    operator: "BRS Travels",
    busType: "AC Seater (2+3)",
    layoutType: "SEATER_2_3",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "14:30",
    arrivalTime: "23:30",
    duration: "9h 00m",
    date: "17 Sep 2026",
    price: 560,
    seats: 45,
    rating: 4.0,
    reviews: "710",
    amenities: ["WiFi", "Charging", "Water Bottle"],
  },
  {
    id: 18,
    operator: "SRS Travels Express",
    busType: "Volvo Multi-Axle Couple Sleeper (2+1)",
    layoutType: "SLEEPER_COUPLE_2_1",
    from: "Bengaluru",
    to: "Pune",
    departureTime: "23:59",
    arrivalTime: "08:15",
    duration: "8h 16m",
    date: "17 Sep 2026",
    price: 990,
    seats: 36,
    rating: 4.9,
    reviews: "4.2K",
    amenities: ["WiFi", "Couple Berths", "Charging", "Snacks", "Live Tracking"],
  },
];

export default busData;